[package]
name = "rpg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.7", features = ["derive"] }
lazy_static = "1.4.0"
owo-colors = "3.5.0"
rand = "0.8.5"
regex = "1.10.2"
